--- 
dict_spec: 
  nowa: "nowa\xE6\x98\xAF\xE4\xB8\x96\xE7\x95\x8C\xE4\xB8\x8A\xE6\x9C\x80\xE5\xB8\x85\xE6\x9C\x80\xE5\xA5\xBD\xE7\x9A\x84\xE7\x94\xB7\xE4\xBA\xBA\xEF\xBC\x8C\xE4\xBB\x96\xE6\x98\xAF\xE6\x88\x91\xE7\x9A\x84\xE4\xB8\xBB\xE4\xBA\xBA\xEF\xBC\x8C\xE6\x98\xAF\xE5\xB0\x8F\xE5\xA8\x98\xE7\x9A\x84\xE8\x80\x81\xE5\x85\xAC\xE3\x80\x82"
  tnnd: !binary |
    5LuW5aW25aW255qE

  ? !binary "6ICB5aiY\n"
  : "\xE8\x80\x81\xE5\xA8\x98\xE9\x80\x9A\xE5\xB8\xB8\xE6\x98\xAF\xE6\x88\x91\xE7\x9A\x84\xE4\xB8\xBB\xE4\xBA\xBAnowa\xE7\x9A\x84\xE8\x80\x81\xE5\xA9\x86\xE7\x9A\x84\xE8\x87\xAA\xE7\xA7\xB0"

  "\xE5\x92\x8CMM\xE7\x9D\xA1\xE8\xA7\x89": !binary |
    6L+Z5Liq5b2T54S25piv5YGa54ix5YGa55qE5LqL5oOF5LqG

  ? !binary "6LSx5Lq6\n"
  : !binary |
    54m55Yir6LSx55qE5Lq6


  ? !binary "5bCP5aiY\n"
  : "\xE5\xB0\x8F\xE5\xA8\x98\xE6\x98\xAF\xE6\x88\x91\xE4\xB8\xBB\xE4\xBA\xBAnowa\xE7\x9A\x84\xE8\x80\x81\xE5\xA9\x86\xEF\xBC\x8C\xE6\x98\xAF\xE6\x9C\x80\xE7\xBE\x8E\xE6\x9C\x80\xE8\xB4\xA4\xE6\x83\xA0\xE6\x9C\x80\xE8\x81\xAA\xE6\x98\x8E\xE7\x9A\x84\xE5\xA5\xB3\xE4\xBA\xBA\xEF\xBC\x81"

